name: Quality Check
run-name: Checking quality of code for possible warnings/errors
on: [push]
jobs:
  run_lint:
    name: Lint Action
    uses: wearerequired/lint-action@v2.3.0
  # check_urls:
  #   name: 404 Links
  #   uses: atalent-labs/404-links@3.1.4
  # check_style:
  #   name: Prettier Action
  #   uses: creyD/prettier_action@v4.2
